version: '3.8'

services:
  api:
    container_name: api
    build: ./api
    ports:
      - 4000:4000
    volumes:
      - ./api/api:/app
    depends_on:
      - database
    env_file:
      - api.env
    command: >
      sh -c "
        /app/wait-for-it.sh database:5432 -t 60 &&
        mix ecto.create &&
        mix ecto.migrate &&
        mix phx.server
      "
    
  front:
    container_name: front
    build: ./front
    ports:
      - 8080:8080
    volumes:
      - ./front:/app
    depends_on:
      - api
      - database
  
  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
