version: '3.8'

services:
  api:
    container_name: api
    build: ./api
    ports:
      - 4000:4000
    volumes:
      - ./api/api:/app
    depends_on:
      - database
    env_file:
      - api.env
    
  front:
    container_name: front
    build: ./front
    ports:
      - 8080:8080
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - api
      - database
    command: npm run serve
  
  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
