version: '3.8'

services:
  api:
    build: ./api
    command: >
      sh -c "
        while ! pg_isready -h database -p 5432 -U postgres; do
          echo 'Waiting for PostgreSQL...'
          sleep 2
        done
        echo 'PostgreSQL is ready!'
        mix deps.get && 
        mix ecto.create && 
        mix ecto.migrate && 
        mix phx.server
      "
    environment:
      - MIX_ENV=dev
    depends_on:
      - database
    
  front:
    container_name: front
    build: ./front
    ports:
      - 8080:8080
    volumes:
      - ./front:/app
    depends_on:
      - api
      - database
  
  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
