name: Build and Test Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: > 
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Build and test the API
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.13.4'
        otp-version: '24.1'

    - name: Install dependencies for API
      run: |
        cd api
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Run entrypoint.sh
      run: |
        cd api
        chmod +x entrypoint.sh
        ./entrypoint.sh

    # Build and test the Frontend
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies for Frontend
      run: |
        cd front
        npm install

    - name: Run Frontend build
      run: |
        cd front
        npm run build

    # Build Docker images (but no push)
    - name: Build Docker images
      run: |
        docker build -t front ./front
        docker build -t api ./api
